### ISSUE TITLE
NPM Package Version Mismatch

### ISSUE THREAD

**Issue by drewpc** [redfin/react-server#736]
When installing `react-server` using `generator-react-server`, it installs version 0.4.9.  When running an `npm install` with the resulting package.json file on a different machine, npm complains that there is no 0.4.9 version of `react-server` listed in the registry.

``` shell
$ npm show generator-react-server

{ name: 'generator-react-server',
  description: 'A react-server yeoman generator',
  'dist-tags': { latest: '0.4.9', prerelease: '0.3.0-beta.4' },
  versions: 
   [ '0.0.6',
     '0.0.7',
     '0.0.9',
     '0.0.10',
     '0.2.6',
     '0.2.10',
     '0.2.11',
     '0.2.12',
     '0.3.0-beta.0',
     '0.3.0-beta.1',
     '0.3.0-beta.2',
     '0.3.0-beta.3',
     '0.3.0-beta.4',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.3.3',
     '0.4.1',
     '0.4.2',
     '0.4.3',
     '0.4.4',
     '0.4.6',
     '0.4.7',
     '0.4.8',
     '0.4.9',
     '1.0.0' ],
```

Looking at the `react-server` entry:

``` shell
$ npm show react-server

{ name: 'react-server',
  'dist-tags': { latest: '0.4.8', prerelease: '0.3.0-beta.4' },
  versions: 
   [ '0.0.1',
     '0.0.2',
     '0.0.3',
     '0.0.4',
     '0.0.5',
     '0.0.6',
     '0.0.7',
     '0.0.9',
     '0.0.10',
     '0.0.11',
     '0.0.22',
     '0.0.23',
     '0.0.24-roblg-npmignore',
     '0.0.24',
     '0.0.26',
     '0.0.27',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.1.4',
     '0.1.5',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.6',
     '0.2.9',
     '0.2.10',
     '0.2.12',
     '0.3.0-beta.0',
     '0.3.0-beta.1',
     '0.3.0-beta.2',
     '0.3.0-beta.3',
     '0.3.0-beta.4',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.3.3',
     '0.3.4',
     '0.4.1',
     '0.4.2',
     '0.4.4',
     '0.4.5',
     '0.4.6',
     '0.4.7',
     '0.4.8' ],
```

Can you please update the NPM registry with the latest version of `react-server`?

**Comment by gigabo** [comment]
Hi @drewpc, we've just published [`v0.4.10`](https://github.com/redfin/react-server/releases/tag/v0.4.10).  Is this still causing you trouble?

**Comment by drewpc** [comment]
0.4.9 still isn't published, but everything else is up to 0.4.13.  Thanks!
